# -*- coding: utf-8 -*-
"""anvarjon.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qdeO9uG0soFR_zjxCcAUZIUjX97ci5D
"""

import numpy as np
# 1. Massiv yaratish
array_1d = np.array([3,4,5,6,7])
array_2d = np.array([[3,4,5,],[4,5,6]])

#2. Matematik operatsiyalar
sum_array = np.sum(array_1d)
mean_array = np.mean(array_1d)
product_array = np.prod(array_1d)

print("1D MASSIV: ",array_1d)
print("2D MASSIV:\n", array_2d)
print("Massivlar yig'indisi: ",sum_array)
print("O'rtacha: ", mean_array)
print("Ko'paytma: ", product_array)

import pandas as pd

# 1. Ma'lumotlar
data = {
    'Ism' : ["Anvarjon", 'Muhammad', 'Samandar','Sadulla','Javohir','Abdurasul','Sarvarjon','Shohruh','Ozodbek','Omadbek'],
    'Yoshi' : [19, 19, 19, 18, 22, 19, 24, 19, 19, 20],
    'Shahar' : ['Namangan', 'Farg`ona', 'Farg`ona', 'Farg`ona', 'Farg`ona', 'Farg`ona', 'Marg`ilon', 'Farg`ona', 'Qo`qon', 'Farg`ona']
}

# 2. DataFrame yaratish
df = pd.DataFrame(data)

# 3. Ma'lumotlarni ko`rish
print(df)

# 4. Filtrlash (ustun nomi 'Yoshi' bo'lishi kerak)
young_people = df[df['Yoshi'] < 20]
print("20 yoshdan kichiklar;\n", young_people)

# 5. O`zgartirish (Yoshini 1 ga kamaytirish)
df['Yoshi'] -= 1
print("Yangilangan DataFrame;\n", df)

# 6. Excel formatda saqlash (to'g'ri funksiya nomi: to_excel)
df.to_excel('541.xlsx', index=True, sheet_name="541")